"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AFundamentalDispute__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var AFundamentalDispute__factory_1 = require("./AFundamentalDispute__factory");
Object.defineProperty(exports, "AFundamentalDispute__factory", { enumerable: true, get: function () { return AFundamentalDispute__factory_1.AFundamentalDispute__factory; } });
